### ISSUE TITLE
PreGen Forge not generating with the correct radius North and West of the center

### ISSUE THREAD

**Issue by naughtius-maximus-8492** [TerraForged/PreGenForge#4]
Hello,

I'm generating a TF world for Vanilla use. I'll go through my steps in detail.

Install the latest version of Forge as of today (31.1.63)
Install the latest version of TerraForged and PreGenForge (0.0.13 and 0.1.0 respectively)
Start a singleplayer world in creative and select world gen type as TerraForged (no settings were changed, just default TF settings).

I set the world spawn to the center (/setworldspawn 0 63 0)
Then I run the pregenerator with /pregen start 0 0 62 minecraft:overworld to generate a radius of about 1000 blocks around spawn.
Run /pregen notify to show me when it's done.
When it's done, I close singleplayer and open up the saves folder and copy the contents of New World and paste it into a fresh Paper server hosted locally. The only plugin installed on the server is Dynamic Map to visualise the issue.

I then render a flat map for Dynamic Map, wait for it to finish, and this comes up https://imgur.com/qhZzCH2
The spawn on the dynamic map shows the point which is 0, 0 but it's 500 blocks from spawn to the edge of the dynmap on the North and West sides but East and South show 1000 blocks from spawn to the edge.

I've also verified that at the edge of the North and West borders 500 blocks from spawn, the generation doesn't continue https://imgur.com/Tu2qGJF.

Here are the logs which I got when generating in PregenForge https://pastebin.com/ZP0hEE6W

**Comment by dags-** [comment]
That looks about right.

PGF generates chunks by the region (32x32 chunks) - this is to make 'world stitching', trimming and other tasks easier.

The spawn point (0, 0) is the lower corner of a 32x32 region.
The below image should help you visualize this:

![grid](https://user-images.githubusercontent.com/4276064/80816132-dc0f5800-8bc6-11ea-8cfd-9995574cbd87.jpg)

**Comment by naughtius-maximus-8492** [comment]
Ah, that makes a lot of sense, thank you!
