### ISSUE TITLE
CPU utilisation is poor

### ISSUE THREAD

**Issue by johnyuki** [TerraForged/PreGenForge#8]
Not sure if this is a forge issue or a mod issue, but whenever I run a pregeneration on my world for a radius of 2516 chunks it barely uses 15% of my CPU (see screenshots below). In addition to this the console keeps getting spammed with "Can't keep up! Is the server overloaded?" messages. I've given the server 10GB of RAM to use, and I have a Ryzen 3800x. The only mods I have installed on the server are the TerraForged and PreGenForge mods. 

https://i.imgur.com/yO0Uiai.png

https://i.imgur.com/5Fyc77n.png

You can see from the second screenshot that activity on some threads is effectively 0%, whereas on the threads that are actually being somewhat utilised they barely get above 40%.

**Comment by Won-Ton** [comment]
Yeah unfortunately this is how minecraft is designed. The amount of cpu horsepower it spends on doing chunk generation each tick is pretty heavily capped to avoid other parts of the game lagging. It'll use at most 8 threads (a mojang imposed limit) so the theoretical best-case utilisation percentage for chunk gen would max out at 50% on a 16core cpu.

I have found a couple of ways to squeeze a bit more throughput on PGF's side so keep an eye out for 0.1.2 on curseforge. Might not be earth shattering though
