### ISSUE TITLE
Center argument does not work

### ISSUE THREAD

**Issue by gamax92** [TerraForged/PreGenForge#9]
When I try to do a pregen around a certain area, my x z coordinates get ignored and the world spawn location is used instead.

Showing the hidden stack trace from CommandUtils.getCenter gave me the following message:
`IllegalArgumentException: Argument 'center' is defined as LocationInput, not class net.minecraft.util.math.Vec2f`

Using `Vec2Argument.getVec2f(context, "center");` works properly.

**Comment by Won-Ton** [comment]
Confirmed the issue. Should be fixed in 0.1.2.
Note some of the command args will have changed order
